version: '3.3'

services:

  # - server container
  nginx:
    build:
      context: ./nginx

    ports:
      - ${HTTP_PORT}:80
      - ${SSH_PORT}:443

    volumes:
      - ../src:/var/www
      - ./nginx/logs/:/var/log/nginx/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d

    depends_on:
      - php-fpm

    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}

    networks:
      - nginxreverse_proxy
      - web

    restart: always

    
# - php container
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: php-fpm-7.3

    volumes:
      - ../src:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
      #add xdebug config file

    networks:
      - web
      - backend

    restart: always


# - database container    
  database:
    build:
      context: ./database/docker-file

    ports:
      - "${MYSQL_PORT}:3306"
    
    volumes:
      - ./database/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./database/import/:/docker-entrypoint-initdb.d/
      - ./database/data-mount:/var/lib/mysql

    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    networks:
      - backend

    restart: always

# - database web GUI container
  database-web-gui:
    image: phpmyadmin/phpmyadmin

    ports:
      - ${DB_WEB_GUI_PORT}:80

    links:
      - database:mysql

    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=database
      - VIRTUAL_HOST=db-${DOMAIN}
      - LETSENCRYPT_HOST=db-${DOMAIN}

    networks:
      - backend

    restart: always

  node:
    image: node:8.12-alpine
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ../src:/home/node/app

# - network
networks:
  web:
  backend:

  nginxreverse_proxy:
     external: true



